apiVersion: v1
kind: ConfigMap
metadata:
  name: mplace-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  PORT: "3000"
  NEXT_PUBLIC_API_URL: {{ .Values.config.NEXT_PUBLIC_API_URL | quote }}
  MEILISEARCH_URL: "http://meilisearch:7700"
  STORAGE_PROVIDER: {{ .Values.config.STORAGE_PROVIDER | quote }}
