{{- if .Values.meilisearch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mplace.labels" . | nindent 4 }}
    app: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: {{ .Values.meilisearch.image }}
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: mplace-secret
                  key: MEILI_MASTER_KEY
            - name: MEILI_ENV
              value: "production"
            - name: MEILI_NO_ANALYTICS
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: meilisearch
  ports:
    - port: 7700
      targetPort: 7700
{{- end }}
