apiVersion: v1
kind: Secret
metadata:
  name: mplace-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}?schema=public"
  REDIS_URL: "redis://redis:6379"
  MEILI_MASTER_KEY: {{ .Values.meilisearch.masterKey | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
  SENTRY_TRACES_SAMPLE_RATE: {{ .Values.sentry.tracesSampleRate | quote }}
