apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mplace
resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - meilisearch.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
