apiVersion: v1
kind: Secret
metadata:
  name: mplace-secret
  namespace: mplace
type: Opaque
stringData:
  POSTGRES_USER: "mplace"
  POSTGRES_PASSWORD: "mplace-super-secret-change-me"
  POSTGRES_DB: "mplace"
  DATABASE_URL: "postgresql://mplace:mplace-super-secret-change-me@postgres:5432/mplace?schema=public"
  REDIS_URL: "redis://redis:6379"
  MEILI_MASTER_KEY: "masterKeyChangeMe_at_least_16_chars"
  JWT_SECRET: "change-me-to-very-long-random-string"
  SENTRY_DSN: ""
