import type { CatalogListItem, CatalogProduct } from "@/lib/server-catalog"

/** Storefront catalog used when Postgres is unreachable. */
const img = {
  bit: "/assets/img/photos/drill-bit.jpg",
  motor: "/assets/img/photos/mud-motor.jpg",
  gate: "/assets/img/photos/gate-valve.jpg",
  ball: "/assets/img/photos/ball-valve.jpg",
  flange: "/assets/img/photos/flange.jpg",
  coverall: "/assets/img/photos/coverall-fr.jpg",
  h2s: "/assets/img/photos/respirator.jpg",
  pump: "/assets/img/photos/pump.jpg",
  tx: "/assets/img/photos/transmitter.jpg",
  chem: "/assets/img/photos/chemicals.jpg",
  gloves: "/assets/img/photos/gloves.jpg",
  harness: "/assets/img/photos/harness.jpg",
}

export const FALLBACK_CATEGORIES: CatalogListItem[] = [
  { id: "drilling-equipment", name: "Буровое оборудование", slug: "drilling-equipment" },
  { id: "pipeline-valves", name: "Трубопроводы и арматура", slug: "pipeline-valves" },
  { id: "ppe-hse", name: "СИЗ и HSE", slug: "ppe-hse" },
  { id: "pumps-compressors", name: "Насосы и компрессоры", slug: "pumps-compressors" },
  { id: "instrumentation", name: "КИПиА", slug: "instrumentation" },
  { id: "chemicals-fluids", name: "Химия и жидкости", slug: "chemicals-fluids" },
]

export const FALLBACK_SHOPS: CatalogListItem[] = [
  { id: "drilltech-supply", name: "DrillTech Supply", slug: "drilltech-supply" },
  { id: "fieldsafe-ppe", name: "FieldSafe PPE", slug: "fieldsafe-ppe" },
  { id: "pipe-valve-co", name: "Pipe & Valve Co", slug: "pipe-valve-co" },
]

export const FALLBACK_PRODUCTS: CatalogProduct[] = [
  {
    id: "mud-motor-6-75",
    name: 'Mud Motor 6-3/4" 5:6',
    slug: "mud-motor-6-75",
    sku: "DTS-DRL-001",
    priceCents: 485_000_000,
    currency: "RUB",
    stock: 3,
    imageUrl: img.motor,
    categoryId: "drilling-equipment",
    shopId: "drilltech-supply",
    category: { id: "drilling-equipment", name: "Буровое оборудование", slug: "drilling-equipment" },
    shop: { id: "drilltech-supply", name: "DrillTech Supply" },
  },
  {
    id: "pdc-drill-bit-8-5",
    name: 'PDC Drill Bit 8-1/2"',
    slug: "pdc-drill-bit-8-5",
    sku: "DTS-DRL-002",
    priceCents: 192_000_000,
    currency: "RUB",
    stock: 5,
    imageUrl: img.bit,
    categoryId: "drilling-equipment",
    shopId: "drilltech-supply",
    category: { id: "drilling-equipment", name: "Буровое оборудование", slug: "drilling-equipment" },
    shop: { id: "drilltech-supply", name: "DrillTech Supply" },
  },
  {
    id: "centrifugal-pump-4x3",
    name: "Centrifugal Process Pump 4x3-10",
    slug: "centrifugal-pump-4x3",
    sku: "DTS-PMP-001",
    priceCents: 143_520_000,
    currency: "RUB",
    stock: 2,
    imageUrl: img.pump,
    categoryId: "pumps-compressors",
    shopId: "drilltech-supply",
    category: { id: "pumps-compressors", name: "Насосы и компрессоры", slug: "pumps-compressors" },
    shop: { id: "drilltech-supply", name: "DrillTech Supply" },
  },
  {
    id: "drilling-fluid-pack-1t",
    name: "Drilling Fluid Additive Pack (1 t)",
    slug: "drilling-fluid-pack-1t",
    sku: "DTS-CHM-001",
    priceCents: 19_320_000,
    currency: "RUB",
    stock: 20,
    imageUrl: img.chem,
    categoryId: "chemicals-fluids",
    shopId: "drilltech-supply",
    category: { id: "chemicals-fluids", name: "Химия и жидкости", slug: "chemicals-fluids" },
    shop: { id: "drilltech-supply", name: "DrillTech Supply" },
  },
  {
    id: "h2s-escape-kit",
    name: "H2S Escape Respirator Kit",
    slug: "h2s-escape-kit",
    sku: "FSP-PPE-001",
    priceCents: 2_944_000,
    currency: "RUB",
    stock: 40,
    imageUrl: img.h2s,
    categoryId: "ppe-hse",
    shopId: "fieldsafe-ppe",
    category: { id: "ppe-hse", name: "СИЗ и HSE", slug: "ppe-hse" },
    shop: { id: "fieldsafe-ppe", name: "FieldSafe PPE" },
  },
  {
    id: "fr-coverall-cat2",
    name: "FR Coverall CAT2",
    slug: "fr-coverall-cat2",
    sku: "FSP-PPE-002",
    priceCents: 1_738_800,
    currency: "RUB",
    stock: 80,
    imageUrl: img.coverall,
    categoryId: "ppe-hse",
    shopId: "fieldsafe-ppe",
    category: { id: "ppe-hse", name: "СИЗ и HSE", slug: "ppe-hse" },
    shop: { id: "fieldsafe-ppe", name: "FieldSafe PPE" },
  },
  {
    id: "chemical-gloves-class-b",
    name: "Chemical Gloves Class B",
    slug: "chemical-gloves-class-b",
    sku: "FSP-PPE-003",
    priceCents: 490_000,
    currency: "RUB",
    stock: 200,
    imageUrl: img.gloves,
    categoryId: "ppe-hse",
    shopId: "fieldsafe-ppe",
    category: { id: "ppe-hse", name: "СИЗ и HSE", slug: "ppe-hse" },
    shop: { id: "fieldsafe-ppe", name: "FieldSafe PPE" },
  },
  {
    id: "safety-harness-en361",
    name: "Safety Harness EN 361",
    slug: "safety-harness-en361",
    sku: "FSP-PPE-004",
    priceCents: 1_275_000,
    currency: "RUB",
    stock: 35,
    imageUrl: img.harness,
    categoryId: "ppe-hse",
    shopId: "fieldsafe-ppe",
    category: { id: "ppe-hse", name: "СИЗ и HSE", slug: "ppe-hse" },
    shop: { id: "fieldsafe-ppe", name: "FieldSafe PPE" },
  },
  {
    id: "pt-0-100bar",
    name: "Pressure Transmitter 0–100 bar",
    slug: "pt-0-100bar",
    sku: "PVC-INS-001",
    priceCents: 8_050_000,
    currency: "RUB",
    stock: 15,
    imageUrl: img.tx,
    categoryId: "instrumentation",
    shopId: "pipe-valve-co",
    category: { id: "instrumentation", name: "КИПиА", slug: "instrumentation" },
    shop: { id: "pipe-valve-co", name: "Pipe & Valve Co" },
  },
  {
    id: "wn-flange-8-sch40",
    name: 'Weld Neck Flange 8" Sch 40',
    slug: "wn-flange-8-sch40",
    sku: "PVC-VLV-001",
    priceCents: 4_620_000,
    currency: "RUB",
    stock: 25,
    imageUrl: img.flange,
    categoryId: "pipeline-valves",
    shopId: "pipe-valve-co",
    category: { id: "pipeline-valves", name: "Трубопроводы и арматура", slug: "pipeline-valves" },
    shop: { id: "pipe-valve-co", name: "Pipe & Valve Co" },
  },
  {
    id: "ball-valve-4-fb",
    name: 'Ball Valve 4"',
    slug: "ball-valve-4-fb",
    sku: "PVC-VLV-002",
    priceCents: 6_380_000,
    currency: "RUB",
    stock: 18,
    imageUrl: img.ball,
    categoryId: "pipeline-valves",
    shopId: "pipe-valve-co",
    category: { id: "pipeline-valves", name: "Трубопроводы и арматура", slug: "pipeline-valves" },
    shop: { id: "pipe-valve-co", name: "Pipe & Valve Co" },
  },
  {
    id: "gate-valve-6-cl600",
    name: 'Gate Valve 6"',
    slug: "gate-valve-6-cl600",
    sku: "PVC-VLV-003",
    priceCents: 9_140_000,
    currency: "RUB",
    stock: 12,
    imageUrl: img.gate,
    categoryId: "pipeline-valves",
    shopId: "pipe-valve-co",
    category: { id: "pipeline-valves", name: "Трубопроводы и арматура", slug: "pipeline-valves" },
    shop: { id: "pipe-valve-co", name: "Pipe & Valve Co" },
  },
]

export const FALLBACK_CATALOG = {
  products: FALLBACK_PRODUCTS,
  categories: FALLBACK_CATEGORIES,
  shops: FALLBACK_SHOPS,
}

export function findFallbackProduct(id: string) {
  const key = (id || "").trim()
  return (
    FALLBACK_PRODUCTS.find(
      (p) => p.id === key || p.slug === key || p.sku === key,
    ) || null
  )
}
